[package]
name = "instantSTATUS"
version = "0.1.0"
authors = ["paperbenni <paperbenni@gmail.com>"]
edition = "2018"


[dependencies]
dirs = "3.0.2"
x11rb = "0.8.1"
toml = "0.5.8"
clap = "3.0.0-beta.2"

